spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: benkhanoussalaheddine@gmail.com
    password: XXXXX XXXXX XXXXXX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8088
