spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always  # 👈 force l'exécution de data.sql
  h2:
    console:
      enabled: true


server:
  port: 8082
