server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/salaheddinebenkhanous/Desktop/SkyReserve/config-repo
  profiles:
    active: native

